# Generated by Django 3.2.8 on 2021-11-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='file',
            field=models.FileField(default='', max_length=255, upload_to='media', verbose_name='Файл'),
        ),
    ]
